import { Resend } from 'resend'

const TREASURER_EMAIL = 'treasurer@gemwoods.com.au'
const BAR_EMAIL       = 'paynterbar@gemwoods.com.au'
const BAR_NAME        = 'Paynter Bar GemLife Palmwoods'

export const config = { api: { bodyParser: { sizeLimit: '10mb' } } }

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' })

  const apiKey = process.env.RESEND_API_KEY
  if (!apiKey) return res.status(500).json({ error: 'RESEND_API_KEY not configured' })

  const { supplier, date, items, invoiceBase64, invoiceFilename, invoiceMimeType, totalCost } = req.body
  if (!supplier || !items?.length) return res.status(400).json({ error: 'supplier and items required' })

  const rows = items.map(i => `
    <tr>
      <td style="padding:7px 12px;border-bottom:1px solid #e2e8f0;font-size:14px">${i.name}</td>
      <td style="padding:7px 12px;border-bottom:1px solid #e2e8f0;font-size:14px;text-align:center">${i.sku || '-'}</td>
      <td style="padding:7px 12px;border-bottom:1px solid #e2e8f0;font-size:14px;text-align:center;font-family:monospace">${i.qty}</td>
      <td style="padding:7px 12px;border-bottom:1px solid #e2e8f0;font-size:14px;text-align:right;font-family:monospace">${i.unitCost ? '$' + Number(i.unitCost).toFixed(2) : '-'}</td>
      <td style="padding:7px 12px;border-bottom:1px solid #e2e8f0;font-size:14px;text-align:right;font-family:monospace">${i.unitCost ? '$' + (Number(i.unitCost) * Number(i.qty.replace(/[^\d.]/g,''))).toFixed(2) : '-'}</td>
    </tr>`).join('')

  const html = `<!DOCTYPE html>
<html><head><meta charset="UTF-8"></head>
<body style="font-family:Arial,sans-serif;max-width:700px;margin:0 auto;padding:20px;color:#0f172a">
  <div style="background:#1e3a5f;padding:16px 20px;border-radius:8px 8px 0 0">
    <div style="color:#fff;font-size:20px;font-weight:800">Paynter Bar - Stock Receipt</div>
    <div style="color:#94a3b8;font-size:13px;margin-top:4px">GemLife Palmwoods</div>
  </div>
  <div style="border:1px solid #e2e8f0;border-top:none;padding:20px;border-radius:0 0 8px 8px">
    <table style="width:100%;margin-bottom:20px">
      <tr><td style="font-size:13px;color:#64748b;padding:4px 0">Supplier</td><td style="font-size:14px;font-weight:700;padding:4px 0">${supplier}</td></tr>
      <tr><td style="font-size:13px;color:#64748b;padding:4px 0">Date Received</td><td style="font-size:14px;font-weight:700;padding:4px 0">${date}</td></tr>
      <tr><td style="font-size:13px;color:#64748b;padding:4px 0">Items</td><td style="font-size:14px;font-weight:700;padding:4px 0">${items.length}</td></tr>
    </table>
    <table style="width:100%;border-collapse:collapse;margin-bottom:20px">
      <thead>
        <tr style="background:#f1f5f9">
          <th style="padding:8px 12px;text-align:left;font-size:12px;text-transform:uppercase;color:#64748b">Item</th>
          <th style="padding:8px 12px;text-align:center;font-size:12px;text-transform:uppercase;color:#64748b">SKU</th>
          <th style="padding:8px 12px;text-align:center;font-size:12px;text-transform:uppercase;color:#64748b">Qty</th>
          <th style="padding:8px 12px;text-align:right;font-size:12px;text-transform:uppercase;color:#64748b">Unit Cost</th>
          <th style="padding:8px 12px;text-align:right;font-size:12px;text-transform:uppercase;color:#64748b">Line Total</th>
        </tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>
    ${invoiceFilename ? `<p style="font-size:13px;color:#64748b">Invoice attached: ${invoiceFilename}</p>` : '<p style="font-size:13px;color:#94a3b8;font-style:italic">No invoice attached</p>'}
    <hr style="border:none;border-top:1px solid #e2e8f0;margin:20px 0">
    <p style="font-size:12px;color:#94a3b8">Generated by Paynter Bar Hub</p>
  </div>
</body></html>`

  const resend = new Resend(apiKey)
  const attachments = []
  if (invoiceBase64 && invoiceFilename) {
    attachments.push({ filename: invoiceFilename, content: invoiceBase64 })
  }

  try {
    const { data, error } = await resend.emails.send({
      from:        `${BAR_NAME} <receipts@paynterbar.gemwoods.com.au>`,
      to:          [TREASURER_EMAIL],
      cc:          [BAR_EMAIL],
      subject:     `Stock Receipt - ${supplier} - ${date}`,
      html,
      attachments,
    })
    if (error) return res.status(500).json({ error: error.message })
    return res.status(200).json({ ok: true, id: data?.id })
  } catch (err) {
    return res.status(500).json({ error: err.message })
  }
}