import nodemailer from 'nodemailer'

export const config = { api: { bodyParser: { sizeLimit: '20mb' } } }

const FROM      = 'paynterbar@gemwoods.com.au'
const TREASURER = 'treasurer@gemwoods.com.au'
const BAR_CC    = 'paynterbar@gemwoods.com.au'

function buildHtml({ supplier, date, items, totalCost }) {
  const rows = items.map(i => `
    <tr>
      <td style="padding:8px 14px;border-bottom:1px solid #e2e8f0;font-size:14px;color:#0f172a">${i.name}</td>
      <td style="padding:8px 14px;border-bottom:1px solid #e2e8f0;font-size:13px;color:#64748b;text-align:center;font-family:monospace">${i.sku || '-'}</td>
      <td style="padding:8px 14px;border-bottom:1px solid #e2e8f0;font-size:14px;font-weight:700;text-align:center;font-family:monospace">${i.qty}</td>
      <td style="padding:8px 14px;border-bottom:1px solid #e2e8f0;font-size:14px;text-align:right;font-family:monospace">${i.unitCost ? '$' + Number(i.unitCost).toFixed(2) : '-'}</td>
    </tr>`).join('')

  const totalRow = totalCost ? `
    <tr style="background:#f8fafc">
      <td colspan="3" style="padding:10px 14px;font-weight:700;font-size:14px;text-align:right;color:#0f172a">Total</td>
      <td style="padding:10px 14px;font-weight:700;font-size:15px;text-align:right;font-family:monospace;color:#1e3a5f">$${Number(totalCost).toFixed(2)}</td>
    </tr>` : ''

  return `<!DOCTYPE html>
<html><head><meta charset="UTF-8"></head>
<body style="font-family:Arial,sans-serif;max-width:680px;margin:0 auto;padding:24px;color:#0f172a;background:#f8fafc">
  <div style="background:#1e3a5f;padding:20px 24px;border-radius:10px 10px 0 0">
    <div style="color:#fff;font-size:22px;font-weight:800">Paynter Bar - Stock Receipt</div>
    <div style="color:#94a3b8;font-size:13px;margin-top:4px">GemLife Palmwoods</div>
  </div>
  <div style="background:#fff;border:1px solid #e2e8f0;border-top:none;padding:24px;border-radius:0 0 10px 10px">
    <table style="width:100%;margin-bottom:24px">
      <tr><td style="font-size:12px;color:#64748b;padding:4px 0;width:130px">Supplier</td><td style="font-size:15px;font-weight:700;padding:4px 0">${supplier}</td></tr>
      <tr><td style="font-size:12px;color:#64748b;padding:4px 0">Date Received</td><td style="font-size:15px;font-weight:700;padding:4px 0">${date}</td></tr>
      <tr><td style="font-size:12px;color:#64748b;padding:4px 0">Items Received</td><td style="font-size:15px;font-weight:700;padding:4px 0">${items.length} item${items.length !== 1 ? 's' : ''}</td></tr>
    </table>
    <table style="width:100%;border-collapse:collapse;margin-bottom:20px">
      <thead>
        <tr style="background:#f1f5f9">
          <th style="padding:8px 14px;text-align:left;font-size:11px;text-transform:uppercase;color:#64748b;letter-spacing:0.06em;font-weight:600">Item</th>
          <th style="padding:8px 14px;text-align:center;font-size:11px;text-transform:uppercase;color:#64748b;letter-spacing:0.06em;font-weight:600">SKU</th>
          <th style="padding:8px 14px;text-align:center;font-size:11px;text-transform:uppercase;color:#64748b;letter-spacing:0.06em;font-weight:600">Qty</th>
          <th style="padding:8px 14px;text-align:right;font-size:11px;text-transform:uppercase;color:#64748b;letter-spacing:0.06em;font-weight:600">Unit Cost</th>
        </tr>
      </thead>
      <tbody>${rows}${totalRow}</tbody>
    </table>
    ${invoiceFilename ? '<p style="font-size:13px;color:#64748b">Invoice attached: ' + invoiceFilename + '</p>' : ''}
    <p style="font-size:12px;color:#94a3b8;margin:16px 0 0;border-top:1px solid #f1f5f9;padding-top:16px">Generated by Paynter Bar Hub</p>
  </div>
</body></html>`
}

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' })

  const smtpUser = process.env.SMTP_USER
  const smtpPass = process.env.SMTP_PASS

  if (!smtpUser || !smtpPass) {
    return res.status(500).json({ error: 'SMTP credentials not configured. Add SMTP_USER and SMTP_PASS to Vercel environment variables.' })
  }

  const { supplier, date, items, invoiceBase64, invoiceFilename, invoiceMimeType, totalCost } = req.body
  if (!supplier || !items?.length) return res.status(400).json({ error: 'supplier and items required' })

  const transporter = nodemailer.createTransport({
    host:   'smtp.office365.com',
    port:   587,
    secure: false,
    auth:   { user: smtpUser, pass: smtpPass },
    tls:    { ciphers: 'SSLv3', rejectUnauthorized: false },
  })

  const attachments = []
  if (invoiceBase64 && invoiceFilename) {
    attachments.push({
      filename:    invoiceFilename,
      content:     invoiceBase64,
      encoding:    'base64',
      contentType: invoiceMimeType || 'application/octet-stream',
    })
  }

  try {
    await transporter.sendMail({
      from:        `"Paynter Bar" <${FROM}>`,
      to:          TREASURER,
      cc:          BAR_CC,
      subject:     `Stock Receipt - ${supplier} - ${date}`,
      html:        buildHtml({ supplier, date, items, totalCost, invoiceFilename }),
      attachments,
    })
    return res.status(200).json({ ok: true })
  } catch (err) {
    console.error('Send receipt error:', err)
    return res.status(500).json({ error: err.message })
  }
}
