/**
 * lib/onedrive.js
 *
 * Microsoft Graph helper for saving files to OneDrive.
 *
 * Uses a long-lived refresh token stored as an environment variable.
 * One-time setup: see RECEIVE_FEATURE_SETUP.md
 *
 * Required env vars:
 *   ONEDRIVE_CLIENT_ID      – Azure app registration client ID
 *   ONEDRIVE_CLIENT_SECRET  – Azure app client secret
 *   ONEDRIVE_TENANT_ID      – 'consumers' for personal MSA, or your tenant GUID
 *   ONEDRIVE_REFRESH_TOKEN  – Long-lived refresh token (from one-time auth)
 *   ONEDRIVE_FOLDER_PATH    – e.g. "Paynter Bar/Receive Reports"
 */

const TOKEN_URL_BASE = 'https://login.microsoftonline.com';

// ── Token management ──────────────────────────────────────────────────────────

let _cachedToken = null;
let _tokenExpiry = 0;

async function getAccessToken() {
  const now = Date.now();
  if (_cachedToken && now < _tokenExpiry - 60_000) return _cachedToken;

  const tenantId = process.env.ONEDRIVE_TENANT_ID ?? 'consumers';
  const params = new URLSearchParams({
    client_id: process.env.ONEDRIVE_CLIENT_ID,
    client_secret: process.env.ONEDRIVE_CLIENT_SECRET,
    grant_type: 'refresh_token',
    refresh_token: process.env.ONEDRIVE_REFRESH_TOKEN,
    scope: 'https://graph.microsoft.com/Files.ReadWrite.All offline_access',
  });

  const res = await fetch(`${TOKEN_URL_BASE}/${tenantId}/oauth2/v2.0/token`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: params.toString(),
  });

  const data = await res.json();

  if (!res.ok || data.error) {
    throw new Error(
      `OneDrive token error: ${data.error_description ?? data.error ?? res.status}`
    );
  }

  _cachedToken = data.access_token;
  _tokenExpiry = now + data.expires_in * 1000;

  // If a new refresh_token is returned, log it so you can update the env var
  if (data.refresh_token && data.refresh_token !== process.env.ONEDRIVE_REFRESH_TOKEN) {
    console.warn(
      '[onedrive] New refresh token issued — update ONEDRIVE_REFRESH_TOKEN env var:\n',
      data.refresh_token
    );
  }

  return _cachedToken;
}

// ── File upload ───────────────────────────────────────────────────────────────

/**
 * saveFile
 * Uploads (or overwrites) a file to OneDrive.
 *
 * @param {string} filename   e.g. "Receive_2025-05-10.csv"
 * @param {Buffer|string} content   File content
 * @param {'text/csv'|'application/json'|'text/plain'} mimeType
 * @returns {Promise<{ id: string, webUrl: string }>}
 */
export async function saveFile(filename, content, mimeType = 'text/csv') {
  const token = await getAccessToken();

  const folder =
    (process.env.ONEDRIVE_FOLDER_PATH ?? 'Paynter Bar/Receive Reports').replace(
      /^\/|\/$/g,
      ''
    );

  // PUT to /me/drive/root:/{folder}/{filename}:/content  (simple upload, ≤4 MB)
  const encodedPath = folder
    .split('/')
    .map(encodeURIComponent)
    .join('/');

  const url = `https://graph.microsoft.com/v1.0/me/drive/root:/${encodedPath}/${encodeURIComponent(filename)}:/content`;

  const body =
    typeof content === 'string' ? Buffer.from(content, 'utf8') : content;

  const res = await fetch(url, {
    method: 'PUT',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': mimeType,
    },
    body,
  });

  const data = await res.json();

  if (!res.ok) {
    throw new Error(
      `OneDrive upload error ${res.status}: ${data.error?.message ?? JSON.stringify(data)}`
    );
  }

  return { id: data.id, webUrl: data.webUrl };
}

// ── CSV builder ───────────────────────────────────────────────────────────────

/**
 * buildReceiveCsv
 * Generates a CSV string from a receive session.
 *
 * @param {object} opts
 * @param {string} opts.reference
 * @param {string} opts.receivedBy
 * @param {string} opts.locationName
 * @param {Array}  opts.items  [{ name, orderedQty, receivedQty, unit, note }]
 * @returns {string}
 */
export function buildReceiveCsv({ reference, receivedBy, locationName, items }) {
  const timestamp = new Date().toLocaleString('en-AU', {
    timeZone: 'Australia/Brisbane',
  });

  const header = [
    `"Paynter Bar — Goods Received Record"`,
    `"Reference","${reference}"`,
    `"Date/Time","${timestamp}"`,
    `"Received By","${receivedBy ?? 'Bar Manager'}"`,
    `"Location","${locationName ?? 'Paynter Bar'}"`,
    ``,
    `"Item","Ordered Qty","Received Qty","Unit","Note"`,
  ].join('\n');

  const rows = items.map((it) => {
    const note = it.note ? `"${it.note.replace(/"/g, '""')}"` : '""';
    return `"${it.name}","${it.orderedQty ?? ''}","${it.receivedQty}","${it.unit ?? ''}",${note}`;
  });

  const totals = [
    ``,
    `"Total lines received","${items.length}"`,
    `"Generated by","Paynter Bar Hub"`,
  ].join('\n');

  return [header, ...rows, totals].join('\n');
}
