// pages/api/documents/regenerate-po.js
//
// Backfills a missing PO-to-OneDrive link for an order that's already been
// received, where the normal resavePO() path (triggered by editing an item
// on a still-open order) is no longer reachable because receiving clears
// the order out of live orderedItems state. The only surviving record of
// what was actually ordered, at that point, is the receive report CSV this
// order's own receive step already saved — so that's what this reconstructs
// the item list from.
//
// Reachable from PO Documents whenever a row has a receive report but no
// po_onedrive_url — see the "🔄 Regenerate PO" button there.

import { createClient } from '@supabase/supabase-js'
import { buildAndSavePO } from '../../../lib/onedrive'
import { requireAuth } from '../../../lib/session'

const sb = () => createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
)

// Minimal CSV parser — handles quoted fields with embedded commas/escaped
// quotes, which is all buildReceiveCsv (lib/onedrive.js) ever produces.
function parseCsvLine(line) {
  const out = []
  let cur = ''
  let inQuotes = false
  for (let i = 0; i < line.length; i++) {
    const ch = line[i]
    if (inQuotes) {
      if (ch === '"') {
        if (line[i + 1] === '"') { cur += '"'; i++ } else { inQuotes = false }
      } else cur += ch
    } else {
      if (ch === '"') inQuotes = true
      else if (ch === ',') { out.push(cur); cur = '' }
      else cur += ch
    }
  }
  out.push(cur)
  return out
}

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' })
  if (!requireAuth(req, res, { allowReadOnly: false })) return

  const { po_ref } = req.body || {}
  if (!po_ref) return res.status(400).json({ error: 'po_ref required' })

  const client = sb()
  const { data: doc, error: docErr } = await client.from('bar_documents')
    .select('*').eq('po_ref', po_ref).order('created_at', { ascending: false }).limit(1).maybeSingle()
  if (docErr) return res.status(500).json({ error: docErr.message })
  if (!doc) return res.status(404).json({ error: 'No PO Documents record found for that reference' })
  if (!doc.receive_report_path) {
    return res.status(400).json({ error: 'No receive report to rebuild the PO from \u2014 if this order hasn\u2019t been received yet, edit any item on it instead (that resaves the PO automatically).' })
  }

  try {
    const { data: fileBlob, error: dlErr } = await client.storage.from('bar-documents').download(doc.receive_report_path)
    if (dlErr) throw new Error('Failed to read receive report: ' + dlErr.message)
    const csvText = await fileBlob.text()
    const lines = csvText.split('\n').filter(l => l.trim())

    const headerIdx = lines.findIndex(l => l.startsWith('"Item"'))
    if (headerIdx === -1) throw new Error('Receive report format not recognised')

    const items = lines.slice(headerIdx + 1)
      .filter(l => l.trim() && !l.startsWith('"Generated by"'))
      .map(line => {
        const cols = parseCsvLine(line)
        const name = cols[0]
        // Prefer the originally ordered qty; fall back to received qty if
        // the ordered column is blank (older receive reports, edge cases).
        const orderedQty = Number(cols[1])
        const receivedQty = Number(cols[2])
        const orderQty = orderedQty > 0 ? orderedQty : (receivedQty > 0 ? receivedQty : 0)
        return { name, orderQty }
      })
      .filter(i => i.name && i.orderQty > 0)

    if (!items.length) throw new Error('No items found in the receive report')

    const { webUrl } = await buildAndSavePO({ po_ref: doc.po_ref, supplier: doc.supplier, order_date: doc.order_date, items })
    if (!webUrl) throw new Error('OneDrive save did not return a link')

    const { error: updErr } = await client.from('bar_documents')
      .update({ po_onedrive_url: webUrl, updated_at: new Date().toISOString() })
      .eq('id', doc.id)
    if (updErr) throw new Error('Saved to OneDrive but failed to link it: ' + updErr.message)

    return res.json({ ok: true, webUrl, itemCount: items.length })
  } catch (e) {
    console.error('[regenerate-po]', e.message)
    return res.status(500).json({ error: e.message })
  }
}
