import ExcelJS from 'exceljs'
import { getAccessToken } from '../../../lib/onedrive'

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' })

  if (!process.env.ONEDRIVE_CLIENT_ID || !process.env.ONEDRIVE_CLIENT_SECRET) {
    return res.status(200).json({ skipped: true, reason: 'OneDrive not configured' })
  }

  const { po_ref, supplier, order_date, items } = req.body
  if (!po_ref || !items?.length) return res.status(400).json({ error: 'po_ref and items required' })

  const NAVY = 'FF1E3A5F', WHITE = 'FFFFFFFF', LGREY = 'FFF1F5F9'
  const date = order_date || new Date().toLocaleDateString('en-AU', { timeZone: 'Australia/Brisbane', day: '2-digit', month: 'short', year: 'numeric' })

  try {
    const wb = new ExcelJS.Workbook()
    const ws = wb.addWorksheet('Purchase Order')

    ws.views = [{ state: 'frozen', ySplit: 6 }]
    ws.columns = [
      { key: 'item',    width: 42 },
      { key: 'sku',     width: 14 },
      { key: 'qty',     width: 12 },
      { key: 'bottles', width: 12 },
      { key: 'unit',    width: 10 },
    ]

    // Title
    const titleRow = ws.addRow(['Paynter Bar — Purchase Order', '', '', '', ''])
    titleRow.getCell(1).font = { bold: true, size: 14, color: { argb: NAVY } }
    titleRow.height = 22

    // Metadata
    const meta = (label, val) => {
      const r = ws.addRow([label, val, '', '', ''])
      r.getCell(1).font = { size: 10, color: { argb: 'FF64748B' } }
      r.getCell(2).font = { size: 10, bold: true, color: { argb: 'FF0F172A' } }
    }
    meta('Supplier', supplier)
    meta('Date', date)
    meta('PO Reference', po_ref)
    meta('Items', String(items.length))
    ws.addRow([])

    // Header
    const hRow = ws.addRow(['Item', 'SKU', 'Order Qty', 'Bottles', 'Unit'])
    hRow.eachCell(cell => {
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: NAVY } }
      cell.font = { bold: true, color: { argb: WHITE } }
      cell.alignment = { horizontal: ['Order Qty','Bottles'].includes(cell.value) ? 'right' : 'left', vertical: 'middle' }
    })
    hRow.height = 18

    // Data
    items.forEach((item, i) => {
      const bg = { type: 'pattern', pattern: 'solid', fgColor: { argb: i % 2 === 0 ? LGREY : WHITE } }
      const row = ws.addRow([item.name, item.sku || '', item.orderQty, item.bottlesToOrder || '', item.isSpirit ? 'nips' : 'units'])
      row.getCell(1).fill = bg; row.getCell(1).font = { size: 12 }
      row.getCell(2).fill = bg; row.getCell(2).font = { size: 11, color: { argb: 'FF64748B' } }
      row.getCell(3).fill = bg; row.getCell(3).font = { bold: true }; row.getCell(3).alignment = { horizontal: 'right' }
      row.getCell(4).fill = bg; row.getCell(4).alignment = { horizontal: 'right' }
      row.getCell(5).fill = bg; row.getCell(5).font = { size: 11, color: { argb: 'FF64748B' } }
    })

    ws.addRow([])
    ws.autoFilter = { from: 'A6', to: 'E6' }
    const foot = ws.addRow(['Paynter Bar — GemLife Palmwoods', '', '', '', 'Generated by Paynter Bar Hub'])
    ;[1,5].forEach(c => { foot.getCell(c).font = { size: 9, italic: true, color: { argb: 'FF94A3B8' } } })

    const buf = await wb.xlsx.writeBuffer()
    const safeSupplier = (supplier || 'Unknown').replace(/[^a-zA-Z0-9 ]/g, '').trim()
    const filename = `${po_ref.replace(/\s/g, '_')}-PO.xlsx`
    const folder = `POs Invoices and Receive Reports/Purchase Orders/${safeSupplier}`
    const encodedPath = folder.split('/').map(encodeURIComponent).join('/')
    const token = await getAccessToken()
    const url = `https://graph.microsoft.com/v1.0/me/drive/root:/${encodedPath}/${encodeURIComponent(filename)}:/content`

    const uploadRes = await fetch(url, {
      method: 'PUT',
      headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' },
      body: buf,
    })
    if (!uploadRes.ok) {
      const err = await uploadRes.json().catch(() => ({}))
      throw new Error(err.error?.message || `Upload failed ${uploadRes.status}`)
    }
    const data = await uploadRes.json()
    return res.json({ ok: true, filename, webUrl: data.webUrl })
  } catch (e) {
    console.error('[save-po]', e.message)
    return res.status(200).json({ skipped: true, reason: e.message })
  }
}
